name: campaign_connect
description: CampaignConnect - Political Campaigning App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  permission_handler: ^11.0.1
  flutter_sms: ^2.3.3
  contacts_service: ^0.6.3
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  image_picker: ^1.0.7
  excel: ^4.0.6
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  open_filex: ^4.3.2
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

